version: '3'

services:
  reactapp:
    build: ./
    restart: always
    ports:
      - 3000:3000
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html