version: '3'

services:
  reactapp:
    build: ./
    restart: always
    ports:
      - 3000:3000
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - reactapp